apiVersion: batch/v1
kind: Job
metadata:
  name: debs-acm-flink-solution-job
  namespace: group-4
spec:
  template:
    spec:
      containers:
        - name: debs-acm-flink-solution-container
          image: omariani24/debs-acm-flink-work:latest
          env:
            - name: API_TOKEN
              value: "cxjbvgcftxxjmkhhtgkfivknvxsccgkr"
          resources:
            requests:
              memory: "2Gi"  # Minimum memory requested
            limits:
              memory: "4Gi"  # Maximum memory allowed
      restartPolicy: OnFailure

#version: "2.2"
#services:
#  jobmanager:
#    image: flink:2.0.0-scala_2.12
#    ports:
#      - "8081:8081"
#    command: standalone-job --job-classname com.job.ClassName [--job-id <job id>] [--jars /path/to/artifact1,/path/to/artifact2] [--fromSavepoint /path/to/savepoint] [--allowNonRestoredState] [job arguments]
#    volumes:
#      - /host/path/to/job/artifacts:/opt/flink/usrlib
#    environment:
#      - |
#        FLINK_PROPERTIES=
#        jobmanager.rpc.address: jobmanager
#        parallelism.default: 2
#
#  taskmanager:
#    image: flink:2.0.0-scala_2.12
#    depends_on:
#      - jobmanager
#    command: taskmanager
#    scale: 1
#    volumes:
#      - /host/path/to/job/artifacts:/opt/flink/usrlib
#    environment:
#      - |
#        FLINK_PROPERTIES=
#        jobmanager.rpc.address: jobmanager
#        taskmanager.numberOfTaskSlots: 2
#        parallelism.default: 2
