apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: group-4
  labels:
    app: flink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
        - name: jobmanager
          image: flink:1.20.1-scala_2.12  # Flink image
          imagePullPolicy: Always
          command: ["jobmanager"]
          env:
            - name: FLINK_PROPERTIES
              value: "${FLINK_PROPERTIES}"
          ports:
            - containerPort: 8081  # Flink Web UI port
            - containerPort: 6123  # JobManager RPC port
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-service
  namespace: group-4
spec:
  selector:
    app: flink
    component: jobmanager
  ports:
    - name: flink-webui-port
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: jobmanager-rpc-port
      protocol: TCP
      port: 6123
      targetPort: 6123
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: group-4
  labels:
    app: flink
spec:
  replicas: 4  # Scale based on your parallelism
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: flink:1.20.1-scala_2.12  # Flink image
          imagePullPolicy: Always
          command: ["taskmanager"]
          env:
            - name: FLINK_PROPERTIES
              value: "${FLINK_PROPERTIES}"  # Set FLINK_PROPERTIES as environment variable
          volumeMounts:
            - name: artifacts-volume
              mountPath: /opt/flink/usrlib/artifacts  # Mount directory containing JAR
          ports:
            - containerPort: 6121  # TaskManager data port
            - containerPort: 6122  # TaskManager Task slot port
      volumes:
        - name: artifacts-volume
          hostPath:
            path: /Users/owenmariani/Desktop/School/junior-year/cs455/team-debs-2-debs-dubs/flink-solution/target/  # Directory path
            type: Directory
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-job-deployment
  namespace: group-4
  labels:
    app: flink-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-job
  template:
    metadata:
      labels:
        app: flink-job
    spec:
      containers:
        - name: flink-job-container
          image: omariani24/debs-acm-flink-work:latest
          imagePullPolicy: Always
          env:
            - name: API_TOKEN
              value: "cxjbvgcftxxjmkhhtgkfivknvxsccgkr"
          resources:
            limits:
              memory: "4Gi"
              cpu: "2"
            requests:
              memory: "2Gi"
              cpu: "1"
          ports:
            - containerPort: 8081
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: flink-job-service
  namespace: group-4
spec:
  selector:
    app: flink-job
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP

---
apiVersion: batch/v1
kind: Job
metadata:
  name: flink-job
  namespace: group-4
spec:
  template:
    spec:
      containers:
        - name: flink-job-container
          image: omariani24/debs-acm-flink-work:latest  # Replace with actual Docker Hub image
          imagePullPolicy: Always
          env:
            - name: API_TOKEN
              value: "cxjbvgcftxxjmkhhtgkfivknvxsccgkr"
          resources:
            limits:
              memory: "4Gi"
              cpu: "2"
            requests:
              memory: "2Gi"
              cpu: "1"
      restartPolicy: Never
